const enum DECK_REDUCER_ACTIONS {
    INIT,
    DECK_REPLACE__PURE,
    DECK_REPLACE__DISCARD_TO_PURE,
    DECK_REMOVE__PURE_TOP,
    DECK_REMOVE__PURE_SPECIFIC,
    DECK_REMOVE__DISCARD_SPECIFIC,
    DECK_ADD__DISCARD_BOT,
}

export default DECK_REDUCER_ACTIONS;
