const enum INIT_RULES_REDUCER_ACTIONS {
    DRAW_INCREMENT,
    DRAW_DECREMENT,
    PLAY_INCREMENT,
    PLAY_DECREMENT,
    HAND_LIMIT_INCREMENT,
    HAND_LIMIT_DECREMENT,
    KEEPER_LIMIT_INCREMENT,
    KEEPER_LIMIT_DECREMENT,
    LOCATION_RIGHT,
    LOCATION_LEFT,
    TELEBLOCK_ON,
    TELEBLOCK_OFF,
    RESET,
}

export default INIT_RULES_REDUCER_ACTIONS;
