const enum PLAYER_REDUCER_ACTIONS {
    INIT,
    HAND_CARDS__ADD,
    HAND_CARDS__REMOVE,
    KEEPER_CARDS__ADD,
    KEEPER_CARDS__REMOVE,
    KEEPER_CARDS__EXCHANGE,
    KEEPER_COOLDOWN__SET,
    TRADE_HANDS,
}

export default PLAYER_REDUCER_ACTIONS;
