const enum RULE_REDUCER_ACTIONS {
    INIT,
    RULE_CHANGE__DRAW,
    RULE_CHANGE__PLAY,
    RULE_CHANGE__KEEPER_LIMIT,
    RULE_CHANGE__HAND_LIMIT,
    RULE_CHANGE__LOCATION,
    RULE_CHANGE__LOCATION_RANDOM,
    RULE_CHANGE__TELEBLOCK,
    RULE_RESET__CHOICE,
    RULE_RESET__ALL,
}

export default RULE_REDUCER_ACTIONS;
